### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by hovissimo** [shirou/mqttcli#10]
```
pi@octopi:~ $ go get github.com/shirou/mqttcli
# golang.org/x/sys/unix
gocode/src/golang.org/x/sys/unix/asm_linux_arm.s:8 5a: No such file or directory: textflag.h
```

This is on the latest Octorprint (built on Raspbian, built on Debian) on a Raspberry Pi.

I don't know Go, but maybe this is something to do with ARM?

**Comment by shirou** [comment]
I don't have ARM, but from the error, it may be Go arm problem.

**Comment by sks** [comment]
@hovissimo : I had some changes on [my fork](https://github.com/sks/mqttcli) which might be of interest.

@shirou : If you are okay with [travis](travis-ci.org) ,Cross compiling your binaries  and using github to share the artifacts. I can create a [PR](https://github.com/shirou/mqttcli/compare/master...sks:master) for this.

**Comment by shirou** [comment]
@sks Thanks. Contribution is always welcome! I can create on Travis to enable your PR.
